### ISSUE TITLE
Inline Parameters

### ISSUE THREAD

**Issue by spjmurray** [couchbase/service-broker#11]
Template configuration parameters are good in that they are validated by Kubernetes' JSON schema validation before being processed by the service broker.  However they are quite bloated:

```yaml
template: {}
parameters:
- name: p1
  source:
    registry: p1
  destinations:
  - path: /p1
parameters:
- name: p2
  source:
    registry: p2
  destinations:
  - path: /p2
parameters:
- name: p3
  source:
    parameter: /p3
  default:
    string: p3
  destinations:
  - path: /p3
```

The proposal here is to allow short form configuration by placing the template parameters inline e.g.

```yaml
template:
  p1: '{{ registry p1 }}'
  p2: '{{ registry p2 }}'
  p3: '{{ parameter /p3 "p3" }}'
```

This has the potential to minimize configuration and make it more legible at the expense of "compile time" type checking.

## Behavior

The object attribute is defined in the template therefore implying that the parameter is *required*, leaving the attribute value as nil may have unintended consequences, and trying to remove the attribute on lookup failure is hard.

## Syntax

The proposal is to leave nothing implicit, therefore an inline parameter must have a lookup type.  If _registry_, the next argument must be a registry key string.  If _parameter_, the next argument must be a JSON pointer. Inline parameters may have a default if the lookup does not exist, these are specified as JSON.

The initial proposal is for simple accessors to begin with.  While I feel formatters would be a popular option there needs to be some further thought e.g.

```yaml
service: '{{ format "%v.%v.svc" instance-name namespace }}'
```

vs

```yaml
service: '{{ format "%v.%v.svc" registry instance-name registry namespace }}'
```

There is a toss-up between being explicit vs implicit for argument lookups.  In all honesty we know format arguments come from an accessor, and there is no ambiguity between a registry key and a JSON pointer (double check registry keys cannot start with `/`).

## Language

Inline parameters are all encoded as strings e.g. valid YAML/JSON types.  They use the `{{ }}` eye-catcher deliberately as it looks familiar to helm users.

Tokens are white-space separated.  Tokens that have an implicit type e.g. function type, are directly converted to that type and errors reported.  Things that have no fixed type e.g. defaults, are specified as JSON so they may be a string, bool, number, array or object as desired.

**Comment by spjmurray** [comment]
One thing to note when considering inline formatting is how does one distinguish between a variadic argument and a default if an argument lookup fails?  Pipelines in helm, if we are trying to keep things similar allow the output of one thing to chain into the next:

```yaml
value: '{{ parameter /my-parameter | default "cat" }}'
```

If we were so inspired, the default function would return "cat" when the input from the previous function was nil.

**Comment by spjmurray** [comment]
Consider also generating DNS SANs, this is a long process at present requiring a great many registry entries, we should be able to condense this down as follows:

```yaml
- name: server-cert
  required: true
  source:
    generateCertificate:
      key:
        registry: server-key
      subject:
        commonName: Couchbase Server
      lifetime: '8760h'
      usage: Server
      alternativeNames:
        dns:
        - inline: '{{ format "%s-srv" instance-name }}'
        - inline: '{{ format "%s-srv.%s" instance-name namespace }}'
        - inline: '{{ format "%s-srv.%s.svc" instance-name namespace }}'
        - inline: '{{ format "*.%s" instance-name }}'
        - inline: '{{ format "*.%s.%s" instance-name namespace }}'
        - inline: '{{ format "*.%s.%s.svc" instance-name namespace }}'
        - literal:
            string: localhost
      ca:
        certificate:
          registry: ca-cert
        key:
          registry: ca-key
  destinations:
  - registry: server-cert
```
