### ISSUE TITLE
Management of Port Pools

### ISSUE THREAD

**Issue by toabi** [couchbase/service-broker#51]
If I want to expose a lot of TCP services, I potentially need a lot of load balancers. Instead of having a dedicated LB per service it would be cool to reuse one load balancer for multiple services.

*But* for this to work I somehow need to know which public ports on an LB I already used.

## Real-life example

When I provision a database for usage outside of the cluster I have to expose it with a load balancer (LB). When I would want to do this with 100+ DBs I need 100+ of LBs. It would be nicer to have all DB instances in the back reachable by the same LB but on different public ports.

I could have an LB pointing at traefik listening on a whole port range (entry points named e.g. tcp-pool-$port) and configure it dynamically with [IngressRouteTCP](https://docs.traefik.io/routing/providers/kubernetes-crd/#kind-ingressroutetcp) when creating a new service instance.

Let's assume we know that we have have 4000, 4001, 4002 still unused on the LB, we can create three of those for our `mongodb-instance-x` which has three nodes.

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mongodb-instance-x-rs0-0  # other IngressRouteTCP for …rs0-1 and …rs0-2
spec:
  entryPoints:
    - tcp-pool-4000  # other IngressRouteTCP for -4001 and 4002
  routes:
  - match: HostSNI(`*`)
    services:
    - name: mongodb-instance-x-rs0-0  # … pointing to rs0-1 and …rs0-2
       port: 27017 
```

And to the service requestor I can hand out a connection string á la `mongodb://my.lb:4000,my.lb:4001,my.lb:4002`.

### Port-Pool Management in the Broker

The Broker would get a new template variable to get one or more known to be free ports from a range.

Something like `getFreePorts(pool string, from int, to int, count int)`

`Pool` would be a string, e.g. "mongodb-lb1", `from` would be the start range and `to` the end (e.g. 40000 and 42000) and the count how many ports I need in my template. This would a list with free ports to use in the template. One would probably store the result directly in the registry.

After handing out the ports, the service-broker will persist them. Maybe as `used-ports-$pool` on the service binding or service instance so in the future it can give out new ports without overlapping. Maybe a global state for the ports would be more efficient that to loop over all already created secrets?

### Possibility to talk with HTTP API from servicebrokerconfig

Instead of managing it in the broker, a third party could do it but the broker would have to make it possible to fetch values from somewhere else.

More problematic than fetching the values from somewhere would be the update on deletion of the service instance. There would maybe have to be some hook where you can an HTTP request á la "DELETE port-manager/$pool-name/$ports". 🤷 

### Something I didn't think of which solves the problem too 

❓ 🤷‍♂️ 😆
