### ISSUE TITLE
Ability to populate credentials registry key via referenced K8s secret

### ISSUE THREAD

**Issue by joshisa** [couchbase/service-broker#81]
**Is your feature request related to a problem? Please describe.**
I have a scenario whereby my broker configuration is creating template resources for a service-instance and service-binding.  These work well with the newish Step and ReadyCheck functionality and provision a service well.  The connection information is expectedly created in a similarly named secret.   However, my problem is that my CloudFoundry end-users will not have direct access or awareness to that secret - so my broker must act as a middle-man.  Therefore, my broker configuration needs a way of being configured to know that my `credentials` snippet is a base64 decoded string residing within a secret named "foo".  This string represents the JSON payload that needs to be fed to the registry credentials key for surfacing by the broker.

**Describe the solution you'd like**
I realize that service catalogs could help ease my pain, but unfortunately I cannot depend on the service catalog feature being present within the k8s cluster.  I would like to create a broker configuration whereby I can define a service-instance  named "CoolCloudService" with a plan named "standard" that takes two parameters: `service-class` and `service-plan`.  This service instance is comprised of two templates.
Template 1 may look roughly like:
```
  - name: some-service-instance
    template:
      apiVersion: my.coolcloud.com/v1
      kind: Service
      metadata:
        name: '{{ registry "instance-name" }}'
        namespace: '{{ registry "coolcloud-serviceinstance-namespace" }}'
        labels:
          my.coolcloud.com/service-class: '{{ parameter "/service-class" }}'
          my.coolcloud.com/service-plan: '{{ parameter "/service-plan" }}'
      spec:
        plan: '{{ parameter "/service-plan" }}' 
        serviceClass: '{{ parameter "/service-class" }}'
```
Template 2 may look roughly like:
```
  - name: some-service-binding
    template:
      apiVersion: my.coolcloud.com/v1
      kind: Binding
      metadata:
        name: '{{ registry "instance-name" }}'
        namespace: '{{ registry "coolcloud-serviceinstance-namespace" }}'
        labels:
          my.coolcloud.com/service-class: '{{ parameter "/service-class" }}'
          my.coolcloud.com/service-plan: '{{ parameter "/service-plan" }}'
      spec:
        serviceName: '{{ registry "instance-name" }}'
```

Using `steps` and `readiness gates`, the ultimate result of this service instance provisioning is really creation of a :
- A service instance resource named "foo" + service binding resource named "foo" + a resulting secret named "foo" which contains the binding connection information.

I would like the service broker to propagate the base64 decoded content (which is a JSON payload) from the secret named "foo" into the credentials registry key during the brokers "binding" process.  

**Describe alternatives you've considered**
I was unable to think of a way to use the current built-in accessors (e.g. to read a named secret) and mutators (e.g. to decode a base64 encoded string).  I'd like to propose adding a new mutator to decode Base64 strings and also have a new accessor that can read data from a named secret.  I believe if these two elements existed, I could provide them within the credentials registry key and be able to propagate the contents of the dynamically generated secret into the servicebroker API credential set that's passed during its binding process.

**Additional context**
I realize this is a meta use-case.  Since I'm using the concept of the broker's instance to actually encompass the creation of 3 things: a service-instance + service-binding + service-instance secret containing creds.  Then, during the broker's binding process - I'm wanting to propagate the service-instance secret creds as binding credentials. @spjmurray I welcome your thoughts on whether adding a couple of built-ins is the best way to go ... or if there's some existing mechanics for connecting secrets content into the broker config that I may have overlooked.
